FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    bc \
    bison \
    build-essential \
    flex \
    gcc-aarch64-linux-gnu \
    gcc-arm-linux-gnueabihf \
    git \
    libssl-dev \
    make \
    python3 \
    python3-pip \
    python-dev \
    swig \
    u-boot-tools \
    libgnutls28-dev \
    libncurses-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /linux-build

COPY . .

RUN make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- business_card_defconfig
RUN make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- -j$(nproc) all
RUN make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- -j$(nproc) modules
RUN mkdir -p out
RUN make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- -j$(nproc) modules_install INSTALL_MOD_PATH=out/

ENTRYPOINT ["/bin/bash"]
